### ISSUE TITLE
Import not supported?

### ISSUE THREAD

**Issue by bridgetlane** [zambien/terraform-provider-apigee#21]
Hi! Thanks for writing this provider. I noticed importing state is not supported - are there any restrictions that have blocked this being implemented?

**Comment by zambien** [comment]
Hello, @bridgetlane, nope I just haven't encountered a need to do so.  Could you elaborate on what you are trying to do with some code so that I can understand the issue more?  I found this:

https://www.bogotobogo.com/DevOps/Terraform/Terraform-state-tfstate-import.php

Does that cover what you are trying to do?

**Comment by pryankster** [comment]
I'll add a "me-too" to this issue:  We have an existing Apigee infrastructure (Private EDGE cluster), and I want to import all of the existing settings for products/developers/dev-apps, without having to re-create them manually (especially getting the API keys from Apigee).  I could write a script to do this, but was hoping that I could just import them.

**Comment by zambien** [comment]
@pryankster could you elaborate on your use case?  Is the link which I posted what you want to do or are you looking for a different import function?  I'm glad to try to help out but want to be sure I'm tackling the correct use case.

**Comment by zambien** [comment]
@pryankster gotcha, thanks for the info.  I'll put this on my to-do list.

**Comment by bridgetlane** [comment]
@zambien sorry, just saw this. My use case is the same as @pryankster -- I'd like to use this provider with already existing terraform resources, without having to delete and re-create them. The tutorial you linked is correct, but this provider doesn't support/have an import command built in.

**Comment by zambien** [comment]
No updates as of yet.  Work has been pretty crazy lately so I'm not sure when I'll have time to look into this.   Would be glad if anyone wants to submit a PR. :)

**Comment by zricethezav** [comment]
https://github.com/zambien/terraform-provider-apigee/pull/22 @zambien @pryankster got a couple resources successfully importing

**Comment by zambien** [comment]
@bridgetlane @pryankster does this resolve your current needs?
