### ISSUE TITLE
Managing multiple proxy deployments not working?

### ISSUE THREAD

**Issue by xurxomp** [zambien/terraform-provider-apigee#28]
Hi,

We are trying to use this provider to manage a proxy that has different revisions deployed (revisions with different base paths, so we can have v1 and v2 deployed at the same time).

Starting with an empty Proxy in Apigee, if we create the revisions and deployments using this Apigee Provider, it seems to work fine. But as soon as you try to do something on top of that, the provider gets confused with the actual revision of each "apigee_api_proxy_deployment". It does not keep track.

Easiest way to reproduce this:
1- Create two apigee_api_proxy_deployment resources (one with revision 1 and the other one with revision 2) using the provider.
2- Use "terraform refresh" and check how the revision of both apigee_api_proxy_deployment is now revision 2 but nothing has really been changed. They should still have revision 1 and revision 2.

Not sure if https://github.com/zambien/terraform-provider-apigee/issues/21 will also fix this.

Thanks

**Comment by zambien** [comment]
This is a separate issue from #21.  I had never considered having two proxies deployed at once to the same environment.  Seems like a normal use case so I'll have to look into this more.

**Comment by zambien** [comment]
@xurxomp please see #38

**Comment by tibers** [comment]
May be related - I am getting back "400 - empty bundle" from the API when I try to `for_each` the proxy. Maybe I'm doing it wrong? I wasn't clear if I was supposed to build an `archive_file` per proxy or not.
```
data "archive_file" "bundle" {
   for_each     = {for r in var.resources: r.customer_name => r}
   type         = "zip"
   source_dir   = "${path.module}/proxy_files"
   output_path  = "${path.module}/proxy_files_bundle/${each.value["customer_name"]}-apiproxy.zip"
}

resource "apigee_api_proxy" "tf_managed_proxy" {
   for_each     = {for r in var.resources: r.customer_name => r}
   name         = each.value["customer_name"]
   bundle       = data.archive_file.bundle[each.key].output_path
   bundle_sha   = data.archive_file.bundle[each.key].output_sha  # The SHA is used to detect changes for plan/apply.
}
```
