### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by bostrowski13** [zambien/terraform-provider-apigee#33]
Hi,

Is this project still maintained?  Doesn't look like a lot of activity goes on.  Appreciate any feedback.

**Comment by zambien** [comment]
@bostrowski13 this is still maintained.  I haven't done much with it recently but I'm going to take a look at the PRs that are out there now.

**Comment by bostrowski13** [comment]
ok, great.  thank you for the quick response!

**Comment by zambien** [comment]
@bostrowski13 is there something specific you are looking for?

**Comment by bostrowski13** [comment]
i was looking forward to using this, but the perceived inactivity of it here was alittle conerning. 

now that i know that, we'll move forward :)  Code all the things!

**Comment by zambien** [comment]
gotcha
