### ISSUE TITLE
Unsupported block type in some resources

### ISSUE THREAD

**Issue by WeAreGroot** [zambien/terraform-provider-apigee#34]
### Terraform Version
Terraform v0.12.10
Apigee download: terraform-provider-apigee_0.0.16_linux_amd64.tar.gz
On AWS Amazon Linux 2

### Affected Resource(s)
Please list the resources as a list, for example:
- apigee_company
- apigee_developer

### Terraform Configuration Files
```
provider "apigee" {
  org      = "${var.APIGEE_ORG}"
  user     = "${var.APIGEE_USER}"
  password = "${var.APIGEE_PASSWORD}"
}

resource "apigee_company" "helloworld_company" {
   name = "helloworld_company"
   display_name = "some longer description for company"

   attributes {
      DisplayName = "my-awesome-company"
   }
}
```

### Debug Output
```
2019/10/09 19:11:45 [TRACE] buildProviderConfig for provider.apigee: using explicit config only
2019/10/09 19:11:45 [TRACE] GRPCProvider: GetSchema
2019/10/09 19:11:45 [TRACE] GRPCProvider: PrepareProviderConfig

Error: Unsupported block type

  on main.tf line 11, in resource "apigee_company" "helloworld_company":
  11:    attributes {

Blocks of type "attributes" are not expected here. Did you mean to define
argument "attributes"? If so, use the equals sign to assign it a value.

2019/10/09 19:11:45 [TRACE] <root>: eval: terraform.EvalNoop
2019/10/09 19:11:45 [TRACE] <root>: eval: terraform.EvalNoop
```
### Expected Behavior
Successful plan.  

### Actual Behavior
What actually happened?
Error as above: Error: Unsupported block type

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform int`
1. `terraform plan`

### Important Factoids
Failure is on AWS ECS - Amazon Linux 2
v.0.0.16 Darwin version works on on Mac with Terraform v0.11.8

**Comment by WeAreGroot** [comment]
Nevermind, I forgot to do a upgrade on the script.

**Comment by WeAreGroot** [comment]
I needed to update my Terraform script to be v.12 compatible.  I just ran `terraform 0.12upgrade` and it fixed those issues for me.

So for TF v.11
```
resource "apigee_company" "helloworld_company" {
  name         = "helloworld_company"
  display_name = "some longer description for company"

  attributes {
    DisplayName = "my-awesome-company"
  }
}
```

But in TF v.12 the attribute block now needs the = sign:
```
resource "apigee_company" "helloworld_company" {
  name         = "helloworld_company"
  display_name = "some longer description for company"

  attributes = {
    DisplayName = "my-awesome-company"
  }
}
```

**Comment by bostrowski13** [comment]
Oh man, I can't believe I overlooked that.  Thanks!
