### ISSUE TITLE
Error: [ERROR] resourceApiProxyDelete error deleting api_proxy

### ISSUE THREAD

**Issue by tibers** [zambien/terraform-provider-apigee#41]
### Terraform Version
0.12.12
apigee 0.17

### Affected Resource(s)
resourceApiProxyDelete

### Expected Behavior
`terraform destroy` should delete all the resources.

### Actual Behavior
Terraform cannot destroy `api_proxy`s and will error until they are manually deleted via the UI.

### Steps to Reproduce
1. bring down the hello world code (I changed revision to `latest`)
1. seed it with an exploded API zip in `~/proxy_files`
1. `terraform apply`
1. validate everything looks good
1. `terraform destroy`

This will produce an error like:

```
...
apigee_company_app.helloworld_company_app: Destroying... [id=ad649013-01cf-400b-8819-1abebb766ba8]
apigee_target_server.helloworld_target_server_testing: Destroying... [id=c8aa8590-c2b9-47c9-bb04-b26de8b9f916]
apigee_developer_app.helloworld_developer_app: Destroying... [id=c1825e45-17a5-435b-9f6f-951a77c3a811]
apigee_target_server.helloworld_target_server_testing: Destruction complete after 2s
apigee_developer_app.helloworld_developer_app: Destruction complete after 2s
apigee_developer.helloworld_developer: Destroying... [id=53e169d7-9bd0-411e-8770-ec47ebdb5a76]
apigee_company_app.helloworld_company_app: Destruction complete after 3s
apigee_company.helloworld_company: Destroying... [id=31061393-ce1b-490f-9c7a-14cec04a5e97]
apigee_product.helloworld_product: Destroying... [id=434ba16d-3933-49a1-94bb-8b1881e0d989]
apigee_product.helloworld_product: Destruction complete after 1s
apigee_developer.helloworld_developer: Destruction complete after 2s
apigee_api_proxy.helloworld_proxy: Destroying... [id=ad0170dd-3276-4fdd-975a-aea54e6ad83d]
apigee_company.helloworld_company: Destruction complete after 1s

Error: [ERROR] resourceApiProxyDelete error deleting api_proxy: DELETE https://api.enterprise.apigee.com/v1/o/<org>/apis/joshtest: 400 Can not delete Revision 1 of ApiProxy joshtest in organization <org>. Undeploy the ApiProxy and try again.
```

**Comment by zambien** [comment]
The error tells you why it can't undeploy the proxy.  Please take a closer look at the error and do some debugging prior to opening issues.

Error: [ERROR] resourceApiProxyDelete error deleting api_proxy: DELETE https://api.enterprise.apigee.com/v1/o/<org>/apis/joshtest: 400 Can not delete Revision 1 of ApiProxy joshtest in organization <org>. Undeploy the ApiProxy and try again.

Hint: is the org really: <org> ?

**Comment by tibers** [comment]
No, I'm anonymizing my issues. The org is correct, which is how I provisioned this in the first place. :)

**Comment by zambien** [comment]
Got it.

Can you post the code that caused this issue?  So long as the proxy_deployment references the proxy via resources (and not a hard-coded name) the destruction should occur in the correct order.  It is also important to keep the revision in sync with the terraform code.  If that is updated out of band you will have to make an update in the terraform code or just use "latest".

**Comment by tibers** [comment]
https://gist.github.com/tibers/374e5b5fb0d907d04ffab3b82266f3fb Thanks for looking into this!

**Comment by zambien** [comment]
OK, I see an issue.  I think this is an issue with a race condition in the Apigee API where the proxy is undeployed but it really isn't complete so when the proxy delete is issued it fails.  I'm introducing retry logic for the delete.

This used to work without these issues.  Stay tuned.

**Comment by zambien** [comment]
Fix is out there for this issue.  Thanks for reporting it and sorry for the confusion on my part.

https://github.com/zambien/terraform-provider-apigee/releases/tag/v0.0.18

**Comment by tibers** [comment]
It looks good. I verify that 0.0.18 doesn't error out anymore on delete.

I did create some resources, and then tried immediately deleting them. I also created some resources, and then I waited 10 minutes, then I deleted them. These didn't produce any errors.  Thanks!
