### ISSUE TITLE
Error after creation of apigee_api_proxy_deployment

### ISSUE THREAD

**Issue by bostrowski13** [zambien/terraform-provider-apigee#43]
I am experiencing the following error after an apri proxy deployment.  It looks like the proxy deployment completes successfully with all resources being created as expected, but (I suspect) it is an issue with calling "resourceApiProxyDeploymentRead" after the "resourceApiProxyDeploymentCreate" completes.  Given the error, I think it has to do with the type associated with the environment in the "resourceApiProxyDeploymentRead".

I think this is also not writing this back to the TF state as well because of the failed call.

### Terraform Version
0.12.9

### Affected Resource(s)
apigee_api_proxy_deployment

### Terraform Configuration Files
```hcl
resource "apigee_api_proxy_deployment" "proxy_deployment" {
  depends_on = [
    apigee_api_proxy.proxy,
    apigee_target_server.target_server
  ]
  proxy_name = apigee_api_proxy.proxy.name
  org        = lookup(var.apigee_org, var.environment, (lookup(var.apigee_org, "default")))
  env        = lookup(var.apigee_environments, var.environment, (lookup(var.apigee_environments, "default")))
  override   = true
  revision   = local.apigee-revision
}
```

### Debug Output
```
resourceApiProxyDeploymentUpdate error deploying: json: cannot unmarshal array into Go struct field ProxyRevisionDeployment.environment of type string

on apigee.tf line 82, in resource "apigee_api_proxy_deployment" "proxy_deployment":
  82: resource "apigee_api_proxy_deployment" "proxy_deployment"
```

### Expected Behavior
While the deployment of the api proxy deployment resource completes and the proxy deployment is deployed successfully, it fails with the noted error.

### Actual Behavior
Threw the error above is thrown.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Using provider version 0.0.18

**Comment by zambien** [comment]
This is the same as #40 .  Closing.
