### ISSUE TITLE
apigee_product got struck in "Still creating" during terraform apply

### ISSUE THREAD

**Issue by sairamaj** [zambien/terraform-provider-apigee#62]
During terraform apply apigee_product resource gets struck indefinitely . If I go to Apigee portal and see the product, it is created successfully. Did anyone see this behavior?

apigee_product.test_api_product: Still creating... [50s elapsed]
apigee_product.test_api_product: Still creating... [1m0s elapsed]
apigee_product.test_api_product: Still creating... [1m10s elapsed]

versions:
Terraform v0.12.24
+ provider.apigee v0.0.22

thank you

**Comment by sairamaj** [comment]
Update on this. It is nothing to do with api_product. If I add couple of resources (in this case I added 2 more shared flows) and now it got struck in shared flow deployment like below

module.test-api-sharedflows.apigee_shared_flow_deployment.access_token_mapper_deployment: Still creating... [1m50s elapsed]
module.test-api-sharedflows.apigee_shared_flow_deployment.fiserv_api_shared_flow_deployment: Still creating... [1m50s elapsed]
module.test-api-sharedflows.apigee_shared_flow_deployment.access_token_mapper_deployment: Still creating... [2m0s elapsed]
module.test-api-sharedflows.apigee_shared_flow_deployment.fiserv_api_shared_flow_deployment: Still creating... [2m0s elapsed]

**Comment by sairamaj** [comment]
When I commented this line: https://github.com/zambien/go-apigee-edge/blob/e45257f962621c84bbffd0a371cbd94cab709d6a/apigee_edge.go#L243 things were working as expected. 
Is printing to standard output in provider could cause the problem?

**Comment by zambien** [comment]
@sairamaj I haven't been able to reproduce this issue.  Are you still seeing a problem?  If so we can reopen the issue.
