### ISSUE TITLE
Feature request: terraform registry.

### ISSUE THREAD

**Issue by PaulRudin** [zambien/terraform-provider-apigee#64]
With the upcoming terraform 13, it's possible for any provider to be automatically installed when configured if there's an appropriate registry entry. 

This would save the need to manually install the provider.

**Comment by rjw57** [comment]
I believe the work here is pretty trivial. I think @zambien need only visit https://registry.terraform.io/publish/provider and select this repo. The existing releases are 90% of the way there according to https://www.terraform.io/docs/registry/providers/publishing.html.
