### ISSUE TITLE
bundle and bundle_sha not set on api_proxy import

### ISSUE THREAD

**Issue by PaulRudin** [zambien/terraform-provider-apigee#65]
Importing an api_proxy doesn't set the bundle and bundle_sha attributes.

This means that if you do e.g. terraform plan immediately after import, then terraform thinks it needs to create them on the imported resource.

**Comment by zambien** [comment]
Importing the bundle sha isn't possible from apigee since apigee knows nothing about it.  This is a value that is set in the terraform state only.  I'm closing this for that reason.
