### ISSUE TITLE
401 Unauthorized error. When trying to create targetServer using terraform.

### ISSUE THREAD

**Issue by swapna0211950** [zambien/terraform-provider-apigee#74]
Hi Team,

We are trying to deploy targetServers to Apigee X env using terraform. But im getting the below error.

Status 401: Message: Unauthorized: on target-server.tf line 1, in resource "apigee_target_server" "example": 1: resource "apigee_target_server" "example"

The Service Account that is used for deployment has Apigee org-admin access. But still this issue is occurring. Any insights on the issue?

**Comment by glorianduka** [comment]
Hi! Were you able to figure out the issue with this error? I am having similar problems and can't seem to find a solution for it

**Comment by psaini0212** [comment]
I am getting same!
