### ISSUE TITLE
the latest macosx release reports version 0.0.0 with terraform v0.11.2

### ISSUE THREAD

**Issue by Mistobaan** [zambien/terraform-provider-apigee#9]
The latest macosx release reports version 0.0.0 with terraform v0.11.2 and is not enabled giving then the "apigee not found error"
```
2018/01/31 22:19:20 [WARNING] found legacy provider "terraform-provider-apigee-v0.0.8_x4"
2018/01/31 22:19:20 [DEBUG] found valid plugin: "apigee-v0.0.8_x4", "0.0.0", "~/terraform/terraform.d/plugins/darwin_amd64/terraform-provider-apigee-v0.0.8_x4"
```
```
terraform init --plugin-dir=~/terraform/terraform.d/plugins/darwin_amd64
```
```
Initializing provider plugins...

Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* apigee (0.0.8)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/darwin_amd64
``

**Comment by zambien** [comment]
How is this issue affecting you?  Is the issue only that terraform is seeing an incorrect version number?

**Comment by Mistobaan** [comment]
ha investigating a bit more I found the issue is in the name, terraform picks the last - as the name:

- NOT WORKING: `terraform-provider-apigee-v0.0.8_x4`  
vs
- WORKING `terraform-provider-apigee_v0.0.8_x4`

maybe rename the release ?

**Comment by zambien** [comment]
I notice you have a:

```
_x4
```
which is mixed with the dashes on the end of your filename..  That isn't how it is named in the release.  
What happens if you just use:

terraform-provider-apigee-v0.0.8

I think that the above is the correct way.

**Comment by Mistobaan** [comment]
@zambien I thought so too, but that is the standard suffix that the terraform adds when doing terraform init (not sure what it means).  I suspect something has changed in the logic that parses the name of the plugin and so the apigee plugin name is picked up as `apigee-v0.0.8` with no version

**Comment by zambien** [comment]
Ok.  I found this issue on the terraform GH repo:

https://github.com/hashicorp/terraform/issues/16874

Do you have a .terraformrc file that is not matching?  That is what the issue reporter was seeing.

**Comment by zambien** [comment]
@Mistobaan I updated the release binary file names.

Sorry for all the back and forth.... this is an odd issue because I don't have this problem on my Mac or when using Virtualbox running Ubuntu Linux.  I have been trying to recreate the issue but have not been successful.

**Comment by Mistobaan** [comment]
Yeah is an annoying detail but that is the spec and seems that now is getting enforced.

> The naming scheme for provider plugins is `terraform-provider-NAME_vX.Y.Z`, and Terraform uses the name to understand the name and version of a particular provider binary. Third-party plugins will often be distributed with an appropriate filename already set in the distribution archive so that it can be extracted directly into the plugin directory described above.

from: https://www.terraform.io/docs/configuration/providers.html

I also have another plugin that does not have that exact naming and it reports `version=0.0.0`
see above reference.

**Comment by zambien** [comment]
Good to know.  Thanks!

**Comment by zambien** [comment]
The latest release has the proper naming conventions.  I had meant to close this but forgot.  Please let me know if you experience other issues and thanks for the contribution!
